'use server'

import prisma from '@/lib/prisma'
import { runSecureServerAction } from '@/lib/auth-utils'
import { Prisma } from '@prisma/client'
import { SystemResponse } from '@/types'

export interface OnboardingPayload {
  tenantName: string;
  unitId: string;
  baseRent: number;
  securityDeposit: number;
  moveInDate: string; // ISO date string
}

export async function submitOnboarding(data: OnboardingPayload): Promise<SystemResponse> {
  return runSecureServerAction('MANAGER', async (session) => {
    try {
      const unit = await prisma.unit.findUnique({ where: { id: data.unitId } });
      if (!unit) return { success: false, message: "Unit not found", errorCode: "VALIDATION_ERROR" };
      
      // Maintenance State Machine: Blocks DECOMMISSIONED units
      if (unit.maintenanceStatus === 'DECOMMISSIONED') {
        return { success: false, message: "Unit is DECOMMISSIONED. Onboarding blocked.", errorCode: "STATE_CONFLICT" };
      }

      const moveIn = new Date(data.moveInDate);
      const year = moveIn.getUTCFullYear();
      const month = moveIn.getUTCMonth();
      
      // Get the last day of the current month
      const endOfMonth = new Date(Date.UTC(year, month + 1, 0));
      const daysInMonth = endOfMonth.getUTCDate();
      const currentDay = moveIn.getUTCDate();
      
      // Inclusive remaining days
      const remainingDays = daysInMonth - currentDay + 1;
      
      // The Proration Engine Math
      const proratedRentRaw = (data.baseRent / daysInMonth) * remainingDays;
      const proratedRent = new Prisma.Decimal(proratedRentRaw.toFixed(2));
      const secDep = new Prisma.Decimal(data.securityDeposit);

      // We'll use random UUIDs generated by DB, so we'll just create them inline
      const result = await prisma.$transaction(async (txOps) => {
        // Step 1: Create Tenant
        const tenant = await txOps.tenant.create({
          data: { name: data.tenantName }
        });

        // Step 2: Create Lease
        // Ending one year from moveInDate
        const endDate = new Date(moveIn);
        endDate.setUTCFullYear(endDate.getUTCFullYear() + 1);

        const lease = await txOps.lease.create({
          data: {
            tenantId: tenant.id,
            unitId: data.unitId,
            isPrimary: true, // First lease is primary
            rentAmount: new Prisma.Decimal(data.baseRent),
            startDate: moveIn,
            endDate,
            isActive: true
          }
        });

        // Step 3: The "Day One" Transaction Charges
        // Charge Record 1: Security Deposit
        await txOps.charge.create({
          data: {
            tenantId: tenant.id,
            leaseId: lease.id,
            // Mapping Deposit as a Late_Fee type temporarily as per constrained PRD enum, or RENT. 
            // PRD didn't give SECURITY_DEPOSIT. We'll use RENT since it's a primary setup cost.
            type: 'RENT', 
            amount: secDep,
            amountPaid: new Prisma.Decimal(0),
            dueDate: moveIn,
            isFullyPaid: false,
          }
        });

        // Charge Record 2: First Month's Prorated Rent
        await txOps.charge.create({
          data: {
            tenantId: tenant.id,
            leaseId: lease.id,
            type: 'RENT', 
            amount: proratedRent,
            amountPaid: new Prisma.Decimal(0),
            dueDate: moveIn,
            isFullyPaid: false,
          }
        });

        // Step 4: Update Unit
        await txOps.unit.update({
          where: { id: unit.id },
          data: { maintenanceStatus: 'OPERATIONAL' }
        });

        return { tenantId: tenant.id, leaseId: lease.id };
      });

      return { 
        success: true, 
        message: "Day One transaction executed successfully.", 
        data: result 
      };

    } catch (e: any) {
      return { success: false, message: e.message || "Onboarding failed", errorCode: "STATE_CONFLICT" };
    }
  });
}
